version: '3.0'

services:

  ros-unity:
    image: registry.nussi.net/ros:unity
    container_name: ros-unity
    restart: unless-stopped
    command: >
      /bin/bash -c "cd /home/dev_ws
      && source install/setup.bash
      && colcon build
      && source install/setup.bash
      && ros2 run ros_tcp_endpoint default_server_endpoint --ros-args -p ROS_IP:=0.0.0.0"
    ports:
      - 10000:10000
    networks:
      - ros

  ros-foxglove-studio:
    image: ghcr.io/foxglove/studio:latest
    container_name: ros-foxglove-studio
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - ros
  

  ros-foxglove-bridge:
    image: registry.nussi.net/ros:foxglove-bridge
    container_name: ros-foxglove-bridge
    ports:
      - 8765:8765
    networks:
      - ros
  
  # ros-static-transform:
  #   image: registry.nussi.net/ros:foxy-desktop
  #   container_name: ros-static-transform
  #   command: ros2 run tf2_ros static_transform_publisher 0 0 0 0.0 0.0 0.0 odom basis_roboter_base_link
  #   networks:
  #     - ros

  # ros-basis-roboter-state:
  #   image: registry.nussi.net/ros:foxy-desktop
  #   container_name: ros-basis-roboter-state
  #   command: ros2 launch /config/basis_roboter/state.launch.xml
  #   networks:
  #     - ros
  #   volumes:
  #     - ../urdf:/urdf
  #     - ./config:/config
  
  # ros-basis-joint-state:
  #   image: registry.nussi.net/ros:joint-state
  #   container_name: ros-basis-joint-state
  #   command: ros2 launch /config/basis_roboter/joint.launch.xml
  #   networks:
  #     - ros
  #   volumes:
  #     - ../urdf:/urdf
  #     - ./config:/config
  
  ros-service-roboter-state:
    image: registry.nussi.net/ros:general
    container_name: ros-service-roboter-state
    command: ros2 launch /config/service_roboter/state.launch.xml
    networks:
      - ros
    volumes:
      - ../urdf:/urdf
      - ./config:/config
  
  ros-service-joint-state:
    image: registry.nussi.net/ros:general
    container_name: ros-service-joint-state
    command: ros2 launch /config/service_roboter/joint.launch.xml
    networks:
      - ros
    volumes:
      - ../urdf:/urdf
      - ./config:/config

  ros-service-twist-mux:
    image: registry.nussi.net/ros:general
    container_name: ros-service-twist-mux
    command: ros2 launch /config/service_roboter/twist_mux.launch.xml
    networks:
      - ros
    volumes:
      - ./config:/config

  ros-service-controller-manager:
    image: registry.nussi.net/ros:general
    container_name: ros-service-controller-manager
    command: ros2 launch /config/service_roboter/controller_manager.launch.py
    networks:
      - ros
    volumes:
      - ../urdf:/urdf
      - ./config:/config


  # ros-service-slam:
  #   image: registry.nussi.net/ros:slam
  #   container_name: ros-service-slam
  #   command: ros2 launch  slam_toolbox online_async_launch.py params_file:=/config/service_roboter/slam.yaml
  #   networks:
  #     - ros
  #   volumes:
  #     - ./config:/config
  
  # ros-service-localization:
  #   image: registry.nussi.net/ros:localization
  #   container_name: ros-service-localization
  #   command: ros2 launch /config/service_roboter/localization.launch.xml
  #   networks:
  #     - ros
  #   volumes:
  #     - ./config:/config


networks:
  ros: